variables:
  PAGES_DEPLOY: public/${CI_COMMIT_REF_NAME}
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/releases/${CI_COMMIT_TAG}"

stages:
  - install
  - build
  - test
  - quality
  - deploy
  - build-release
  - upload-release
  - release


# Select what we should cache
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/

install:
  image: dockerhub.interpid.eu/php74
  stage: install
  artifacts:
    expire_in: 5 days
    untracked: true
  script:
    - composer install

tests-php70:
  stage: test
  image: dockerhub.interpid.eu/$PHP
  dependencies:
    - install
  script:
    - sh ./bin/phpunit-php70.sh
  parallel:
    matrix:
      - PHP:
          - php71
          - php72

tests-php:
  stage: test
  image: dockerhub.interpid.eu/$PHP
  dependencies:
    - install
  script:
    - vendor/bin/phpunit
  parallel:
    matrix:
      - PHP:
          - php73
          - php74
          - php80
          - php81

code-coverage:
  stage: quality
  image: dockerhub.interpid.eu/php74
  script:
    - echo "xdebug.mode=coverage" >> /etc/php/7.4/cli/php.ini
    - vendor/bin/phpunit --configuration phpunit-ci.xml
    - vendor/bin/phpmetrics --report-html=./build/php/phpmetrics ./library/interpid/PdfLib
  coverage: '/Lines:\s*(\d+\.\d+)/'
  artifacts:
    paths:
      - build
    expire_in: 1 year

#pages:
#  stage: deploy
#  script:
#    - mkdir -p ${PAGES_DEPLOY}
#    - cp -r build/* ${PAGES_DEPLOY}
#  artifacts:
#    paths:
#      - ${PAGES_DEPLOY}

# Run the release build
build-release:
  stage: build-release
  image: dockerhub.interpid.eu/php74
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - php ./bin/build-release.php
    - source ./bin/set-versions.sh
  artifacts:
    paths:
      - release
      - $VARIABLES_FILE
    expire_in: 1 year

upload-release:
  stage: upload-release
  image: curlimages/curl:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - source ./bin/set-versions.sh
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file ./release/fpdf-table-${VERSION_TABLE}.zip ${PACKAGE_REGISTRY_URL}/fpdf-table-${VERSION_TABLE}.zip
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file ./release/fpdf-multicell-${VERSION_MULTICELL}.zip ${PACKAGE_REGISTRY_URL}/fpdf-multicell-${VERSION_MULTICELL}.zip

create-release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG                  # Run this job when a tag is created manually
  script:
    - source ./bin/set-versions.sh
    - |
      release-cli create --name "Release $CI_COMMIT_TAG" --tag-name $CI_COMMIT_TAG \
        --assets-link "{\"name\":\"fpdf-table-${VERSION_TABLE}.zip\",\"url\":\"${PACKAGE_REGISTRY_URL}/fpdf-table-${VERSION_TABLE}.zip\"}" \
        --assets-link "{\"name\":\"fpdf-multicell-${VERSION_MULTICELL}.zip\",\"url\":\"${PACKAGE_REGISTRY_URL}/fpdf-multicell-${VERSION_MULTICELL}.zip\"}" \
