# Select what we should cache
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/

# Run phpunit tests
php72-tests:
  image: klodoma/php72
  script:
    - composer install
    - vendor/bin/phpunit --configuration phpunit-ci.xml
    - vendor/bin/phpmetrics --report-html=./build/phpmetrics ./library/interpid
  artifacts:
    paths:
      - build
    expire_in: 1 year

# Run phpunit tests
php73-tests:
  image: klodoma/php73
  script:
    - composer install
    - vendor/bin/phpunit --configuration phpunit-ci.xml
